// This file is auto-generated by scripts/generate-image-map.js
// Do not edit by hand.

export const imageMap: Record<string, any> = {
  "hanuman.png": require("../../assets/gods/Hanuman.png"),
  "anjanadri.webp": require("../../assets/gods/anjanadri.webp"),
  "kolhapurMahalaxmi.jpg": require("../../assets/gods/kolhapurMahalaxmi.jpg"),
  "shiv.jpg": require("../../assets/gods/shiv.jpg"),
  "Gaangapur.jpg": require("../../assets/gods/Gaangapur.jpg"),
  "shree-tulja-bhavani-temple-the-shakti-peetha-of-tuljapur-and-its-rich-historical-egacy.jpg": require("../../assets/gods/shree-tulja-bhavani-temple-the-shakti-peetha-of-tuljapur-and-its-rich-historical-egacy.jpg"),
  "swamiRaghvendraTemple.jpeg": require("../../assets/gods/swamiRaghvendraTemple.jpeg"),
};

export function getImage(filename?: string) {
  if (!filename) return undefined;
  return imageMap[filename.toLowerCase()];
}
